app:
  couchbase:
    connection-string: couchbase://172.17.0.2
    user-name: Administrator
    password: password
    bucketName: trade

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
